### ISSUE TITLE
spotify.Config Error

### ISSUE THREAD

**Issue by quicon** [jgeigerm/spotify2playmusic#1]
Hi

I'm trying to use your tool spotify2playmusic in Ubuntu
I have followed the README and installed all the requirements but
unfortunately it does not work, I get the following error:

/spotify2playmusic$ python spotify2playmusic.py

Traceback (most recent call last):
 File "spotify2playmusic.py", line 322, in <module>
   main()
 File "spotify2playmusic.py", line 204, in main
   config = spotify.Config()
AttributeError: 'module' object has no attribute 'Config'

I am not an experienced programmer, could you please help me to get it
working?
Thanks

**Comment by BlackLight** [comment]
I have the same error on Linux. Any hints on how to fix it? It apparently looks like pyspotify has a different API on Linux and OSX.

**Comment by BlackLight** [comment]
Ok got it...You are using pyspotify 2 in your code (and spotify.Config() is part of it), which is still beta, while pip install pyspotify still installs 1.11. It's probably worth specifying in the README that pyspotify should be installed via pip install --pre pyspotify until pyspotify 2.0.0 goes out of beta.

**Comment by jgeigerm** [comment]
Ill change that. Thank you for testing it out!!


FIN, ACK
---------------------------------------------------------------------------------
Rochester Institute of Technology '16
Information Security and Forensics
President - RIT Competitive Cybersecurity Club (rc3.club)
President - Kappa Delta Rho, Iota Beta Chapter (kdrib.org)
