### ISSUE TITLE
Large playlists timeout

### ISSUE THREAD

**Issue by yeahdef** [jgeigerm/spotify2playmusic#5]
I found that one of my playlists with 3800+ songs it in was timing out on the track load of the first track in the playlist.

A work-around that enabled me was to increase that timeout.

I did this on line 236:

        track = track.load(timeout=30)

I've never done a 'pull request' nor do I know the proper etiquette regarding pushing changes to a repo I don't control, but maybe this will help someone.

**Comment by jgeigerm** [comment]
I'll update the code on Sunday when I can get back to my computer. Thanks!!
