### ISSUE TITLE
merge changes to existing playlist

### ISSUE THREAD

**Issue by thewrz** [jgeigerm/spotify2playmusic#8]
Right now I notice that if your program detects that the playlist already exists, it will just skip it.

if playlist.load().name in gpm_playlist_names:
        print("Playlist already exists in Google Play... exiting")
        exit()

Any plans on adding a feature where it tries to merge changes? Say you add 30 songs or so to a Spotify playlist, but then want to add those songs to your All Access playlist. Wouldn't it be neat if you could do that.

Again, great work. Very handy.

**Comment by jgeigerm** [comment]
Perhaps. I don't have spotify premium anymore so it's hard for me to test out new things. I'll leave the issue open for now but don't have a timeline.

**Comment by thewrz** [comment]
Makes sense. One day I'll do better than just commenting on other people's work and staring at my "Python Programming third edition for the absolute beginner" book ---- and help out!

Thanks again.
