### ISSUE TITLE
TOO_MANY_ITEMS

### ISSUE THREAD

**Issue by thewrz** [jgeigerm/spotify2playmusic#9]
Is there a limit on how big a Google Play Music playlist can be? Towards the end of trying to add songs to a Spotify playlist with about 1500 tracks, TONS of these messages started barfing back at me in the console:
BatchMutatePlaylistEntries: The server reported failure while changing the requested resource. If this wasn't caused by invalid arguments or server flakiness, please open an issue.
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/plentriesbatch', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'data': '{"mutations": [{"create": {"deleted": false, "trackId": "Txrrtzvzfvl5dcsdmjll6nrmwiy", "lastModifiedTimestamp": "0", "playlistId": "173a9c61-ccc2-4d61-807c-e1772c17cfba", "clientId": "4a3d46e6-d251-11e4-b560-0800272f9997", "source": 2, "creationTimestamp": "-1"}}]}', 'method': 'POST', 'params': {'alt': 'json'}})
(response was: '{\n "mutate_response": [\n  {\n   "response_code": "TOO_MANY_ITEMS"\n  }\n ]\n}\n')
Adding song to playlist Tatr7frzadtbun6rz2ezaperfoe

**Comment by thewrz** [comment]
Oh I see...
https://productforums.google.com/forum/#!topic/play/tCEea8gAKvQ

**Comment by jgeigerm** [comment]
Sorry about that, unfortunately nothing I can do :/
